name = "SerializationCaches"
uuid = "3f9d9eeb-f6fe-486e-aab5-ad2c1ff40024"
authors = ["Beacon Biosignals, Inc."]
version = "0.2.2"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
OrderedCollections = "1.3"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
